apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-c-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: service-c
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
